name: Scan Images In Bahmni Namespace

on:
  workflow_dispatch:

jobs:
  scan-containers:
    name: Scan Images In Bahmni Namespace
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Get Scanner Script and Template File
        run: |
          curl -o container-scanner.sh https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/BAH-3800/container-scanner.sh
          chmod +x container-scanner.sh
          curl -o html.tpl https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/BAH-3800/html.tpl
      - name: Scan Images In Bahmni Namespace
        run: |
          ./container-scanner.sh
      - name: Commit and push changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bahmni Infra] | Add. Image Scan Report ${{ steps.date.outputs.date }}"
          create_branch: true
          branch: report-test
          file_pattern: '*.html'
          repository: .
          commit_user_name: Bahmni Infra
          commit_user_email: infrastructure@bahmni.org
          commit_author: bahmni-infra <infrastructure@bahmni.org>