name: Scan Images In Bahmni Namespace

on:
  workflow_dispatch:

jobs:
  scan-images:
    name: Scan Images In Bahmni Namespace
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout security-private repo
        uses: actions/checkout@v3
        with:
          repository: rahu1ramesh/security-reports
          token: ${{ secrets.GHA_TOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Get Scanner Script and Template File
        run: |
          curl -o image-scanner.sh https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/BAH-3800/image-scanner.sh
          chmod +x image-scanner.sh
          curl -o html.tpl https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/BAH-3800/html.tpl
      - name: Scan Images In Bahmni Namespace
        run: |
          ./image-scanner.sh bahmni
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-scan-summary
          path: container-scanner-reports/bahmni-${{ steps.date.outputs.date }}
      - name: Commit and push changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Rahul] | Add. Image Scan Report ${{ steps.date.outputs.date }}"
          file_pattern: 'image-scan-report/${{ steps.date.outputs.date }}/*.html'
          repository: .
          commit_user_name: Rahul Ramesh
          commit_user_email: rahul.ramesh@thoughtworks.com
          commit_author: rahu1ramesh <rahul.ramesh@thoughtworks.com>